### ISSUE TITLE
Verse comparison seems ... off

### ISSUE THREAD

**Issue by kobsy** [boblail/pericope#14]
Should this be `to_i` instead of `to_a` for `Verse`?
https://github.com/boblail/pericope/blob/1b8c58232fb9d42cc33fdd77c9993a30a4bd9c90/lib/pericope/verse.rb#L28

**Comment by kobsy** [comment]
Nevermind. I don't think I realized `Struct` had a `to_a` method, and this would make good sense for comparing equality. This is what happens when I stay up too late programming. 🤦‍♂️ 😅

**Comment by boblail** [comment]
Haha!

`to_i == other.to_i` would compare `book`, `chapter`, and `verse` but not `letter`.

`to_a == other.to_a` is how Ruby's `Struct`'s define equality (`to_a` and `values` being aliases for each other) so this _reinstates_ the `==` that `Verse` gets from being a `Struct`.

Why do I have to reinstate that `==`? Because `Verse` includes `Comparable` and `Comparable` redefines `==` in terms of `<=>`. Unfortunately, `4 <=> 4a` should be `0` (i.e. they occupy the same position), but they are not equal.

So, for `Verse`, `4 < 4a` and `4 > 4a` are both false and yet `4 ≠ 4a`.

**Comment by kobsy** [comment]
Good to know!
