### ISSUE TITLE
standard way to parse our chapter and verse?

### ISSUE THREAD

**Issue by timfong888** [boblail/pericope#7]
I am guessing that @range lets me extract chapter and verse?

```
@ranges=[35003019..35003019]
```
Is the last three digits always verse, the second three always chapter and the first two digits the book?

**Comment by timfong888** [comment]
So using range, to find the start verse:

```
text[1].ranges.first.first.to_s[5..7]
=> "019"
```
where text[1] is a Pericope object?

I found `well_formed_reference` but I would need to parse differently for 3:15 versus 3:15-17.

Is this the way you intend for us to extract verse.  I have everything else atomized.

**Comment by boblail** [comment]
> Is the last three digits always verse, the second three always chapter and the first two digits the book?
Yes

I don't really use `Pericope#ranges` directly. I use one of these two methods once I've parsed a pericope:

  - `Pericope#intersects?` to compare two pericopes
  - `Pericope#to_a` to list of all the verses in the pericope (w/o ranges, just a flat list)

**Comment by timfong888** [comment]
Hi the chapter seems consistently off by 1.

In this case it should have been Romans 15 but chapter count is 16.

Is this correct?



On Thursday, June 9, 2016, Bob Lail <notifications@github.com> wrote:

> Is the last three digits always verse, the second three always chapter and
> the first two digits the book?
> Yes
>
> I don't really use Pericope#ranges directly. I use one of these two
> methods once I've parsed a pericope:
>
>    - Pericope#intersects? to compare two pericopes
>    - Pericope#to_a to list of all the verses in the pericope (w/o ranges,
>    just a flat list)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/boblail/pericope/issues/7#issuecomment-225044220>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAA259fMFtFSGkfaubTp7R2K3XuLkYKSks5qKJGUgaJpZM4IwncZ>
> .
>


-- 
Sent from Gmail Mobile

**Comment by timfong888** [comment]
```
010:0> p.to_a
=> [#<Pericope:0x0055c7507c0570 @original_string="Romans 10:10", @book=45, @book_name="Romans", @book_chapter_count=16, @ranges=[45010010..45010010]>]
```
I want something to tell me this is chapter 10, verse 10 explicitly.  But it seems like it just gives the book count, not the actual chapter.

**Comment by timfong888** [comment]
For example, it seems like to know chapter, I need to currently do this:

```
p.first.ranges.first.to_s[2..4].to_i.to_s
```

**Comment by lukebooth** [comment]
There isn't an explicit `chapter` or `verse` method on a Pericope object, but you can do something like 

```
p = Pericope.new("Romans 10:13-15")
p.well_formatted_reference
=> "10:13-15"

p = Pericope.new("Romans 8:1-39")
p.well_formatted_reference
=> "8"
```

And if you `split` that reference by `:`, you'll get the chapter and verse (or just chapter if your verse range covers the whole chapter)

**Comment by boblail** [comment]
@timfong888, in your examples, you're sending `to_a` to an _array_ of pericopes:

```ruby
p = Pericope.parse("Romans 10:10")
p.first.ranges.first.to_s[2..4].to_i.to_s
```

`p` isn't a `Pericope`, it's an array.

```ruby
Pericope.parse("Romans 10:10") # => returns an array of pericopes (might be empty)
Pericope.parse_one("Romans 10:10") # => returns a single pericope or nil
```

Also, I wouldn't stringify the range in order to extract the chapter from it. `to_s[2..4]` will fail for single-digit books (Genesis through 1 Samuel). Use `Pericope.get_chapter` instead.

So this is how your code should look (to get the chapter of the first verse in the pericope):

```ruby
p = Pericope.parse_one("Romans 10:10")
Pericope.get_chapter(p.to_a.first)
```

* * *

`Pericope` models any kind of reference
  - single verses (`"Romans 10:10"`)
  - ranges of verses (`"Romans 10:13-15"`)
  - split ranges (`"Romans 10:13-15, 17")
  - ranges that span chapters (`"Romans 10-12"`)

It doesn't respond to `chapter` or `verse` because it might not represent a single chapter or a single verse.

* * *

Here's a potential refactor that might make the API for determining chapter-and-verse of a parsed pericope a little nicer (and feel free to make a pull request for it):

   1. Store verses internally as objects that wrap verse IDs (e.g. `35003019`) but that respond to `book`, `chapter`, and `verse`.
   2. Alias `to_a` as `verses`

Then you'd write the above example as:

```ruby
p = Pericope.parse_one("Romans 10:10")
p.verses.first.chapter
```

**Comment by timfong888** [comment]
@lukebooth -- I was looking for the well_formatted_reference, I had come upon it before, but couldn't find it when listing #methods.  Splitting : to get chapter and then splitting - to get start and end verse might be the way to go.
